[tools]
rust = "stable"

[tasks.build-core]
description = "Build the Rust core library"
run = "cargo build --manifest-path rust/prism_core/Cargo.toml --release"

[tasks.test-core]
description = "Run Rust core tests"
run = "cargo test --manifest-path rust/prism_core/Cargo.toml"

[tasks.fmt-core]
description = "Format Rust sources"
run = "cargo fmt --manifest-path rust/prism_core/Cargo.toml"

[tasks.clippy-core]
description = "Run Clippy on the Rust core library"
run = "cargo clippy --manifest-path rust/prism_core/Cargo.toml --all-targets --all-features -- -D warnings"

[tasks.swift-bindings]
description = "Generate Swift bindings from the UniFFI interface"
run = "cargo run --manifest-path rust/prism_core/Cargo.toml --bin generate_swift"

[tasks.build-xcframework]
description = "Build the universal xcframework for the Rust core"
run = "./scripts/build-xcframework.sh"
