[tools]
rust = "stable"

[tasks.build-rust]
description = "Build all Rust crates"
run = "cargo build --manifest-path rust/Cargo.toml --workspace --release"

[tasks.test-rust]
description = "Run Rust tests across the workspace"
run = "cargo test --manifest-path rust/Cargo.toml --workspace --all-targets"

[tasks.fmt-rust]
description = "Format Rust sources across the workspace"
run = "cargo fmt --manifest-path rust/Cargo.toml --all"

[tasks.lint-rust]
description = "Run Clippy on all Rust crates"
run = "cargo clippy --manifest-path rust/Cargo.toml --workspace --all-targets --all-features -- -D warnings"

[tasks.swift-bindings]
description = "Generate Swift bindings from the UniFFI interface"
run = "cargo run --manifest-path rust/prism_core/Cargo.toml --bin generate_swift"

[tasks.build-xcframework]
description = "Build the universal xcframework for the Rust core"
run = "./scripts/build-xcframework.sh"

[tasks.test-swift]
description = "Run Swift PrismFFI tests"
run = "swift test --package-path swift/PrismFFI"

[tasks.test]
description = "Run all tests (Rust core + Swift FFI)"
run = "cargo test --manifest-path rust/Cargo.toml --workspace --all-targets && swift test --package-path swift/PrismFFI"
